var searchData=
[
  ['scan_201_0',['scan 1',['../index.html#autotoc_md13',1,'dup-scan(1)'],['../index.html#autotoc_md9',1,'scan(1)']]],
  ['scanandcompareasync_1',['ScanAndCompareAsync',['../class_file_integrity_validator_1_1_core_1_1_services_1_1_file_scanner.html#affd90bde4d843bfd19b1a0cdd6118f2e',1,'FileIntegrityValidator::Core::Services::FileScanner']]],
  ['scancommandinput_2',['ScanCommandInput',['../class_file_integrity_validator_1_1_core_1_1_models_1_1_scan_command_input.html',1,'FileIntegrityValidator::Core::Models']]],
  ['scannewdirasync_3',['ScanNewDirAsync',['../class_file_integrity_validator_1_1_core_1_1_services_1_1_file_scanner.html#ad62dc21bfa622dfc902e62a792512f5e',1,'FileIntegrityValidator::Core::Services::FileScanner']]],
  ['scanoptions_4',['ScanOptions',['../class_file_integrity_validator_1_1_cli_1_1_options_1_1_scan_options.html',1,'FileIntegrityValidator::Cli::Options']]],
  ['search_201_5',['search(1)',['../index.html#autotoc_md15',1,'']]],
  ['searchcommandinput_6',['SearchCommandInput',['../class_file_integrity_validator_1_1_core_1_1_models_1_1_search_command_input.html',1,'FileIntegrityValidator::Core::Models']]],
  ['searchfileparser_7',['SearchFileParser',['../class_file_integrity_validator_1_1_core_1_1_services_1_1_search_file_parser.html',1,'FileIntegrityValidator.Core.Services.SearchFileParser'],['../class_file_integrity_validator_1_1_core_1_1_services_1_1_search_file_parser.html#a5ef1adb012139ef45d9c3425dcf02bee',1,'FileIntegrityValidator.Core.Services.SearchFileParser.SearchFileParser()']]],
  ['searchoptions_8',['SearchOptions',['../class_file_integrity_validator_1_1_cli_1_1_options_1_1_search_options.html',1,'FileIntegrityValidator::Cli::Options']]],
  ['searchrecordsbyfilehashesasync_9',['SearchRecordsByFileHashesAsync',['../class_file_integrity_validator_1_1_core_1_1_services_1_1_file_record_searcher.html#aa45f29b3eb21d98ba1cde77699178209',1,'FileIntegrityValidator.Core.Services.FileRecordSearcher.SearchRecordsByFileHashesAsync(List&lt; string &gt; databasesPaths, List&lt; string &gt; fileHashes, ConcurrentDictionary&lt; string, ConcurrentBag&lt; FileRecordNoHash &gt; &gt; recordsDict)'],['../class_file_integrity_validator_1_1_core_1_1_services_1_1_file_record_searcher.html#a2732e92c1dc2bf9d1e48c2e2d0421e5b',1,'FileIntegrityValidator.Core.Services.FileRecordSearcher.SearchRecordsByFileHashesAsync(string databasePath, List&lt; string &gt; fileNames, ConcurrentDictionary&lt; string, ConcurrentBag&lt; FileRecordNoHash &gt; &gt; recordsDict)']]],
  ['searchrecordsbyfilenamesasync_10',['SearchRecordsByFileNamesAsync',['../class_file_integrity_validator_1_1_core_1_1_services_1_1_file_record_searcher.html#a124c43f706417fe49568baed43693fc5',1,'FileIntegrityValidator.Core.Services.FileRecordSearcher.SearchRecordsByFileNamesAsync(List&lt; string &gt; databasesPaths, List&lt; string &gt; fileNames, ConcurrentDictionary&lt; string, ConcurrentBag&lt; FileRecordNoName &gt; &gt; recordsDict)'],['../class_file_integrity_validator_1_1_core_1_1_services_1_1_file_record_searcher.html#ac6c29efdb3cd7377c315d775625745a4',1,'FileIntegrityValidator.Core.Services.FileRecordSearcher.SearchRecordsByFileNamesAsync(string databasePath, List&lt; string &gt; fileNames, ConcurrentDictionary&lt; string, ConcurrentBag&lt; FileRecordNoName &gt; &gt; recordsDict)']]],
  ['string_11',['string',['../class_file_integrity_validator_1_1_infrastructure_1_1_file_i_o_1_1_path_validator.html#a12592770fa798dc356281c3e70e87fc9',1,'FileIntegrityValidator::Infrastructure::FileIO::PathValidator']]],
  ['success_12',['success',['../class_file_integrity_validator_1_1_infrastructure_1_1_file_i_o_1_1_path_validator.html#a6ffe47c30183612063fae9ced33b698e',1,'FileIntegrityValidator::Infrastructure::FileIO::PathValidator']]],
  ['supported_20features_13',['Supported Features',['../index.html#autotoc_md4',1,'']]]
];
